version: '3.4'

services:
  app:
    image: nicolkill/space_travel_calculator
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      MIX_ENV: dev
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:4000/api/v1/health' ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

